local M = {}

function M.apply(p)
  local hi = function(group, opts)
    vim.api.nvim_set_hl(0, group, opts)
  end

  -- Editor
  hi("Normal",         { fg = p.fg,       bg = p.bg })
  hi("NormalFloat",    { fg = p.fg,       bg = p.bg_soft })
  hi("NormalNC",       { fg = p.fg_muted, bg = p.bg })
  hi("ColorColumn",    { bg = p.bg_dim })
  hi("CursorLine",     { bg = p.bg_dim })
  hi("CursorColumn",   { bg = p.bg_dim })
  hi("CursorLineNr",   { fg = p.fg_subtle })
  hi("LineNr",         { fg = p.fg_ghost })
  hi("SignColumn",     { bg = p.bg })
  hi("VertSplit",      { fg = p.border })
  hi("WinSeparator",   { fg = p.border })
  hi("Folded",         { fg = p.fg_faint,  bg = p.bg_dim })
  hi("FoldColumn",     { fg = p.fg_ghost,  bg = p.bg })
  hi("NonText",        { fg = p.border })
  hi("Whitespace",     { fg = p.surface })
  hi("EndOfBuffer",    { fg = p.border })
  hi("MatchParen",     { bg = p.surface })
  hi("Conceal",        { fg = p.fg_faint })

  -- Cursor
  hi("Cursor",         { fg = p.bg, bg = p.cursor })
  hi("CursorIM",       { fg = p.bg, bg = p.cursor })
  hi("TermCursor",     { fg = p.bg, bg = p.cursor })

  -- Search / selection
  hi("Visual",         { bg = p.bg_muted })
  hi("VisualNOS",      { bg = p.bg_muted })
  hi("Search",         { fg = p.fg,  bg = p.overlay })
  hi("IncSearch",      { fg = p.bg,  bg = p.cursor })
  hi("CurSearch",      { fg = p.bg,  bg = p.cursor })
  hi("Substitute",     { fg = p.bg,  bg = p.error })

  -- Popup menu
  hi("Pmenu",          { fg = p.fg,       bg = p.bg })
  hi("PmenuSel",       { fg = p.fg,       bg = p.bg_muted, bold = true })
  hi("PmenuSbar",      { bg = p.bg_dim })
  hi("PmenuThumb",     { bg = p.overlay })

  -- Status / tab line
  hi("StatusLine",     { fg = p.fg_faint, bg = p.bg })
  hi("StatusLineNC",   { fg = p.fg_ghost, bg = p.bg })
  hi("TabLine",        { fg = p.fg_faint, bg = p.bg_subtle })
  hi("TabLineSel",     { fg = p.fg,       bg = p.bg_muted })
  hi("TabLineFill",    { bg = p.bg_subtle })
  hi("WildMenu",       { fg = p.fg,       bg = p.bg_muted })

  -- Messages
  hi("ErrorMsg",       { fg = p.error })
  hi("WarningMsg",     { fg = p.warning })
  hi("ModeMsg",        { fg = p.fg_muted })
  hi("MoreMsg",        { fg = p.info })
  hi("Question",       { fg = p.info })

  -- Spelling
  hi("SpellBad",       { undercurl = true, sp = p.error })
  hi("SpellCap",       { undercurl = true, sp = p.warning })
  hi("SpellRare",      { undercurl = true, sp = p.info })
  hi("SpellLocal",     { undercurl = true, sp = p.hint })

  -- Classic syntax groups
  hi("Comment",        { fg = p.comment,  italic = true })
  hi("Constant",       { fg = p.constant })
  hi("String",         { fg = p.string })
  hi("Character",      { fg = p.string })
  hi("Number",         { fg = p.number })
  hi("Boolean",        { fg = p.constant })
  hi("Float",          { fg = p.number })
  hi("Identifier",     { fg = p.variable })
  hi("Function",       { fg = p.func })
  hi("Statement",      { fg = p.keyword })
  hi("Conditional",    { fg = p.keyword })
  hi("Repeat",         { fg = p.keyword })
  hi("Label",          { fg = p.keyword })
  hi("Operator",       { fg = p.operator })
  hi("Keyword",        { fg = p.keyword })
  hi("Exception",      { fg = p.keyword })
  hi("PreProc",        { fg = p.keyword })
  hi("Include",        { fg = p.keyword })
  hi("Define",         { fg = p.keyword })
  hi("Macro",          { fg = p.decorator })
  hi("PreCondit",      { fg = p.keyword })
  hi("Type",           { fg = p.type })
  hi("StorageClass",   { fg = p.keyword })
  hi("Structure",      { fg = p.type })
  hi("Typedef",        { fg = p.type })
  hi("Special",        { fg = p.decorator })
  hi("SpecialChar",    { fg = p.string })
  hi("Tag",            { fg = p.tag })
  hi("Delimiter",      { fg = p.operator })
  hi("SpecialComment", { fg = p.comment,  italic = true })
  hi("Debug",          { fg = p.error })
  hi("Underlined",     { underline = true })
  hi("Ignore",         { fg = p.fg_ghost })
  hi("Error",          { fg = p.error })
  hi("Todo",           { fg = p.bg, bg = p.warning, bold = true })

  -- Treesitter (Neovim 0.8+)
  hi("@comment",                { link = "Comment" })
  hi("@comment.documentation",  { fg = p.comment, italic = true })
  hi("@keyword",                { link = "Keyword" })
  hi("@keyword.function",       { fg = p.keyword })
  hi("@keyword.operator",       { fg = p.operator })
  hi("@keyword.return",         { fg = p.keyword })
  hi("@keyword.import",         { fg = p.keyword })
  hi("@operator",               { link = "Operator" })
  hi("@punctuation.delimiter",  { fg = p.operator })
  hi("@punctuation.bracket",    { fg = p.operator })
  hi("@punctuation.special",    { fg = p.operator })
  hi("@string",                 { link = "String" })
  hi("@string.escape",          { fg = p.operator })
  hi("@string.special",         { fg = p.decorator })
  hi("@string.regex",           { fg = p.decorator })
  hi("@number",                 { link = "Number" })
  hi("@float",                  { link = "Float" })
  hi("@boolean",                { link = "Boolean" })
  hi("@constant",               { link = "Constant" })
  hi("@constant.builtin",       { fg = p.constant })
  hi("@constant.macro",         { fg = p.decorator })
  hi("@function",               { link = "Function" })
  hi("@function.builtin",       { fg = p.func })
  hi("@function.macro",         { fg = p.decorator })
  hi("@function.call",          { fg = p.func })
  hi("@method",                 { fg = p.func })
  hi("@method.call",            { fg = p.func })
  hi("@constructor",            { fg = p.type })
  hi("@parameter",              { fg = p.variable })
  hi("@variable",               { link = "Identifier" })
  hi("@variable.builtin",       { fg = p.keyword })
  hi("@field",                  { fg = p.property })
  hi("@property",               { fg = p.property })
  hi("@namespace",              { fg = p.namespace })
  hi("@type",                   { link = "Type" })
  hi("@type.builtin",           { fg = p.type })
  hi("@type.definition",        { fg = p.type })
  hi("@type.qualifier",         { fg = p.keyword })
  hi("@attribute",              { fg = p.decorator })
  hi("@tag",                    { fg = p.tag })
  hi("@tag.attribute",          { fg = p.func })
  hi("@tag.delimiter",          { fg = p.operator })
  hi("@text",                   { fg = p.fg })
  hi("@text.title",             { fg = p.keyword, bold = true })
  hi("@text.emphasis",          { fg = p.fg, italic = true })
  hi("@text.strong",            { fg = p.br_white, bold = true })
  hi("@text.literal",           { fg = p.string })
  hi("@text.uri",               { fg = p.func, underline = true })
  hi("@text.reference",         { fg = p.func })
  hi("@text.todo",              { link = "Todo" })
  hi("@text.warning",           { fg = p.warning })
  hi("@text.danger",            { fg = p.error })

  -- Diagnostics
  hi("DiagnosticError",              { fg = p.error })
  hi("DiagnosticWarn",               { fg = p.warning })
  hi("DiagnosticInfo",               { fg = p.info })
  hi("DiagnosticHint",               { fg = p.hint })
  hi("DiagnosticUnderlineError",     { undercurl = true, sp = p.error })
  hi("DiagnosticUnderlineWarn",      { undercurl = true, sp = p.warning })
  hi("DiagnosticUnderlineInfo",      { undercurl = true, sp = p.info })
  hi("DiagnosticUnderlineHint",      { undercurl = true, sp = p.hint })
  hi("DiagnosticVirtualTextError",   { fg = p.error,   italic = true })
  hi("DiagnosticVirtualTextWarn",    { fg = p.warning, italic = true })
  hi("DiagnosticVirtualTextInfo",    { fg = p.info,    italic = true })
  hi("DiagnosticVirtualTextHint",    { fg = p.hint,    italic = true })
  hi("DiagnosticSignError",          { fg = p.error })
  hi("DiagnosticSignWarn",           { fg = p.warning })
  hi("DiagnosticSignInfo",           { fg = p.info })
  hi("DiagnosticSignHint",           { fg = p.hint })

  -- LSP references
  hi("LspReferenceText",    { bg = p.surface })
  hi("LspReferenceRead",    { bg = p.surface })
  hi("LspReferenceWrite",   { bg = p.surface, bold = true })

  -- LSP inlay hints
  hi("LspInlayHint",        { fg = p.fg_subtle, bg = p.bg })

  -- LSP semantic tokens (@lsp.type.*)
  hi("@lsp.type.class",         { link = "@type" })
  hi("@lsp.type.decorator",     { link = "@attribute" })
  hi("@lsp.type.enum",          { link = "@type" })
  hi("@lsp.type.enumMember",    { link = "@constant" })
  hi("@lsp.type.function",      { link = "@function" })
  hi("@lsp.type.interface",     { link = "@type" })
  hi("@lsp.type.macro",         { link = "@constant.macro" })
  hi("@lsp.type.method",        { link = "@method" })
  hi("@lsp.type.namespace",     { link = "@namespace" })
  hi("@lsp.type.parameter",     { link = "@parameter" })
  hi("@lsp.type.property",      { link = "@property" })
  hi("@lsp.type.struct",        { link = "@type" })
  hi("@lsp.type.type",          { link = "@type" })
  hi("@lsp.type.typeParameter", { link = "@type" })
  hi("@lsp.type.variable",      { link = "@variable" })
  hi("@lsp.mod.deprecated",     { strikethrough = true })
  hi("@lsp.mod.readonly",       { link = "@constant" })
  hi("@lsp.mod.static",         { link = "@constant" })

  -- Git signs (gitsigns.nvim)
  hi("GitSignsAdd",         { fg = p.git_add })
  hi("GitSignsChange",      { fg = p.git_change })
  hi("GitSignsDelete",      { fg = p.git_delete })

  -- Diff
  hi("DiffAdd",             { fg = p.git_add,    bg = p.bg_soft })
  hi("DiffChange",          { fg = p.git_change, bg = p.bg_soft })
  hi("DiffDelete",          { fg = p.git_delete, bg = p.bg_soft })
  hi("DiffText",            { fg = p.fg,         bg = p.surface })

  -- Neo-tree
  hi("NeoTreeNormal",              { fg = p.fg,       bg = p.bg })
  hi("NeoTreeNormalNC",            { fg = p.fg_muted, bg = p.bg })
  hi("NeoTreeSignColumn",          { bg = p.bg })
  hi("NeoTreeStatusLine",          { fg = p.fg_faint, bg = p.bg })
  hi("NeoTreeStatusLineNC",        { fg = p.fg_ghost, bg = p.bg })
  hi("NeoTreeVertSplit",           { fg = p.border,   bg = p.bg })
  hi("NeoTreeWinSeparator",        { fg = p.border,   bg = p.bg })
  hi("NeoTreeEndOfBuffer",         { fg = p.border,   bg = p.bg })
  hi("NeoTreeRootName",            { fg = p.fg_muted, bold = true })
  hi("NeoTreeCursorLine",          { bg = p.bg_dim })
  hi("NeoTreeIndentMarker",        { fg = p.border })
  hi("NeoTreeExpander",            { fg = p.fg_faint })
  hi("NeoTreeFloatBorder",         { fg = p.border,   bg = p.bg_soft })
  hi("NeoTreeFloatTitle",          { fg = p.fg_muted, bg = p.bg_soft, bold = true })
  hi("NeoTreeTitleBar",            { fg = p.bg,       bg = p.overlay })
  hi("NeoTreeDirectoryName",       { fg = p.fg_muted })
  hi("NeoTreeDirectoryIcon",       { fg = p.func })
  hi("NeoTreeFileIcon",            { fg = p.fg_subtle })
  hi("NeoTreeFileName",            { fg = p.fg })
  hi("NeoTreeFileNameOpened",      { fg = p.fg, bold = true })
  hi("NeoTreeFilterTerm",          { fg = p.string })
  hi("NeoTreeModified",            { fg = p.git_change })
  hi("NeoTreeMessage",             { fg = p.fg_faint, italic = true })
  hi("NeoTreeDimText",             { fg = p.fg_ghost })
  hi("NeoTreeHiddenByName",        { fg = p.fg_ghost })
  hi("NeoTreeSymbolicLinkTarget",  { fg = p.func })
  hi("NeoTreeDotfile",             { fg = p.fg_ghost })
  hi("NeoTreeGitAdded",            { fg = p.git_add })
  hi("NeoTreeGitConflict",         { fg = p.error })
  hi("NeoTreeGitDeleted",          { fg = p.git_delete })
  hi("NeoTreeGitIgnored",          { fg = p.fg_ghost })
  hi("NeoTreeGitModified",         { fg = p.git_change })
  hi("NeoTreeGitUnstaged",         { fg = p.warning })
  hi("NeoTreeGitUntracked",        { fg = p.git_untracked })
  hi("NeoTreeGitStaged",           { fg = p.git_add })
  hi("NeoTreeTabActive",           { fg = p.fg,       bg = p.bg_muted, bold = true })
  hi("NeoTreeTabInactive",         { fg = p.fg_faint, bg = p.bg_subtle })
  hi("NeoTreeTabSeparatorActive",  { fg = p.border,   bg = p.bg_muted })
  hi("NeoTreeTabSeparatorInactive",{ fg = p.border,   bg = p.bg_subtle })

  -- Terminal colors
  vim.g.terminal_color_0  = p.black
  vim.g.terminal_color_1  = p.red
  vim.g.terminal_color_2  = p.green
  vim.g.terminal_color_3  = p.yellow
  vim.g.terminal_color_4  = p.blue
  vim.g.terminal_color_5  = p.magenta
  vim.g.terminal_color_6  = p.cyan
  vim.g.terminal_color_7  = p.white
  vim.g.terminal_color_8  = p.br_black
  vim.g.terminal_color_9  = p.br_red
  vim.g.terminal_color_10 = p.br_green
  vim.g.terminal_color_11 = p.br_yellow
  vim.g.terminal_color_12 = p.br_blue
  vim.g.terminal_color_13 = p.br_magenta
  vim.g.terminal_color_14 = p.br_cyan
  vim.g.terminal_color_15 = p.br_white
end

return M
